#!/usr/bin/env node

/**
 * Post-build verification for the current Vite + vite-plugin-pwa build.
 *
 * Checks that dist/ contains what the deploy needs:
 *   - index.html referencing hashed JS/CSS assets that actually exist
 *   - the tag search worker chunk
 *   - the service worker generated by vite-plugin-pwa (sw.js + workbox-*.js) and the web manifest
 *   - the static data files fetched at runtime (public/data/*)
 *   - no pre-compressed files (.gz/.br are no longer produced; hosts compress on the fly)
 *     and no JS/CSS that is gzip-encoded on disk (would cause ERR_CONTENT_DECODING_FAILED)
 *
 * Usage: node scripts/verify-build.js [distDir]   (defaults to ./dist)
 * Exits with code 1 if any check fails.
 */

import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

const distPath = path.resolve(process.cwd(), process.argv[2] || 'dist');

let failures = 0;
let warnings = 0;
const ok = (msg) => console.log(`  OK    ${msg}`);
const fail = (msg) => { failures++; console.log(`  FAIL  ${msg}`); };
const warn = (msg) => { warnings++; console.log(`  WARN  ${msg}`); };

if (!fs.existsSync(distPath)) {
  console.error(`dist directory not found: ${distPath}`);
  process.exit(1);
}

/** Recursively list files relative to dist (POSIX separators). */
function listFiles(dir, base = dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...listFiles(full, base));
    else out.push(path.relative(base, full).split(path.sep).join('/'));
  }
  return out;
}

const files = listFiles(distPath);
const fileSet = new Set(files);
const kb = (rel) => (fs.statSync(path.join(distPath, rel)).size / 1024).toFixed(1);

console.log(`Verifying build in ${distPath} (${files.length} files)\n`);

// 1. index.html and the assets it references
console.log('index.html');
if (!fileSet.has('index.html')) {
  fail('index.html missing');
} else {
  const html = fs.readFileSync(path.join(distPath, 'index.html'), 'utf8');
  const refs = [...html.matchAll(/(?:src|href)="\/?(assets\/[^"]+)"/g)].map((m) => m[1]);
  if (refs.length === 0) fail('index.html does not reference any /assets/ files');
  for (const ref of refs) {
    if (fileSet.has(ref)) ok(`${ref} (${kb(ref)} KB)`);
    else fail(`index.html references missing file ${ref}`);
  }
}

// 2. Worker chunk
console.log('\nWorker');
const workerChunks = files.filter((f) => /^assets\/tagSearch\.worker[-.].*\.js$/.test(f));
if (workerChunks.length) workerChunks.forEach((f) => ok(`${f} (${kb(f)} KB)`));
else fail('tag search worker chunk (assets/tagSearch.worker-*.js) not found');

// 3. PWA output from vite-plugin-pwa
console.log('\nPWA');
if (fileSet.has('sw.js')) {
  ok(`sw.js (${kb('sw.js')} KB)`);
  const sw = fs.readFileSync(path.join(distPath, 'sw.js'), 'utf8');
  const workboxRefs = [...sw.matchAll(/workbox-[\w-]+\.js/g)].map((m) => m[0]);
  for (const ref of new Set(workboxRefs)) {
    if (fileSet.has(ref)) ok(`${ref} (referenced by sw.js)`);
    else fail(`sw.js references missing ${ref}`);
  }
  if (!sw.includes('index.html')) warn('sw.js precache manifest does not mention index.html');
} else {
  fail('sw.js missing (vite-plugin-pwa should generate it)');
}
const manifest = ['manifest.webmanifest', 'manifest.json'].find((f) => fileSet.has(f));
if (manifest) ok(manifest);
else fail('web app manifest (manifest.webmanifest / manifest.json) missing');

// 4. Runtime data files
console.log('\nData');
for (const rel of ['data/tags.json', 'data/fuse-index.json', 'data/tag-groups.json', 'data/deepl-languages.json']) {
  if (fileSet.has(rel)) ok(`${rel} (${kb(rel)} KB)`);
  else fail(`${rel} missing`);
}

// 5. Compression sanity
console.log('\nCompression');
const precompressed = files.filter((f) => /\.(gz|br)$/.test(f));
if (precompressed.length) warn(`unexpected pre-compressed files: ${precompressed.slice(0, 5).join(', ')}${precompressed.length > 5 ? ', ...' : ''}`);
else ok('no .gz/.br files');
const gzipEncoded = files
  .filter((f) => /\.(js|css|html)$/.test(f))
  .filter((f) => {
    const fd = fs.openSync(path.join(distPath, f), 'r');
    const buf = Buffer.alloc(2);
    fs.readSync(fd, buf, 0, 2, 0);
    fs.closeSync(fd);
    return buf[0] === 0x1f && buf[1] === 0x8b;
  });
if (gzipEncoded.length) gzipEncoded.forEach((f) => fail(`${f} is gzip-encoded on disk (would cause ERR_CONTENT_DECODING_FAILED)`));
else ok('JS/CSS/HTML are plain text');

// 6. CSP: every inline <script> in index.html must be allowed by its sha256 hash
//    in both host configs, otherwise browsers silently block it in production.
console.log('\nCSP');
if (fileSet.has('index.html')) {
  const html = fs.readFileSync(path.join(distPath, 'index.html'), 'utf8');
  const inlineScripts = [...html.matchAll(/<script(?![^>]*\bsrc=)(?![^>]*type="application\/ld\+json")[^>]*>([\s\S]*?)<\/script>/g)]
    .map((m) => m[1]);
  const configs = ['vercel.json', 'netlify.toml'].filter((f) => fs.existsSync(path.resolve(process.cwd(), f)));
  for (const script of inlineScripts) {
    const hash = `'sha256-${crypto.createHash('sha256').update(script).digest('base64')}'`;
    for (const config of configs) {
      const text = fs.readFileSync(path.resolve(process.cwd(), config), 'utf8');
      if (text.includes(hash)) ok(`${config} allows inline script ${hash}`);
      else fail(`${config} CSP is missing ${hash} for an inline script in index.html (update script-src)`);
    }
  }
  if (inlineScripts.length === 0) ok('no inline scripts');
}

console.log(`\n${failures ? 'FAILED' : 'PASSED'}: ${failures} failure(s), ${warnings} warning(s)`);
process.exit(failures ? 1 : 0);
