import { Suspense, lazy } from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import './index.css'
import './styles/imageOptimizations.css'
import './i18n'

// Vercel Analytics / Speed Insights only exist on Vercel deployments (/_vercel/*);
// the same repo is also deployed to Netlify, where those scripts 404.
const loadVercelInsights = __ON_VERCEL__ && process.env.NODE_ENV === 'production'

const Analytics = loadVercelInsights
  ? lazy(() => import('@vercel/analytics/react').then(module => ({ default: module.Analytics })))
  : () => null

const SpeedInsights = loadVercelInsights
  ? lazy(() => import('@vercel/speed-insights/react').then(module => ({ default: module.SpeedInsights })))
  : () => null

const rootElement = document.getElementById('root')
if (!rootElement) throw new Error('Failed to find the root element')

ReactDOM.createRoot(rootElement).render(
  <>
    <App />
    {loadVercelInsights && (
      <Suspense fallback={null}>
        <Analytics />
        <SpeedInsights />
      </Suspense>
    )}
  </>
)

// Service worker (generated by vite-plugin-pwa / Workbox). Production only, never on localhost.
const isLocalhost = ['localhost', '127.0.0.1', '[::1]'].includes(window.location.hostname)

if (import.meta.env.PROD && !isLocalhost && 'serviceWorker' in navigator) {
  // Remove caches left behind by the old hand-written sw.js (Workbox's
  // cleanupOutdatedCaches only removes its own outdated precaches).
  if ('caches' in window) {
    const legacyCaches = ['static-v1', 'dynamic-v1', 'images-v1']
    legacyCaches.forEach((name) => {
      window.caches.delete(name).catch(() => {})
    })
  }

  import('virtual:pwa-register')
    .then(({ registerSW }) => registerSW({ immediate: true }))
    .catch(() => {})
}
